// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1000","screenHeight":"1000","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_RemoveTitleScreen","status":true,"description":"This Plugin removes the title screen from the game.","parameters":{}},
{"name":"V8tnbPir","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}}
];
